server:
  port: 8080

spring:
  application:
    name: aop
#  task:
#    execution:
#      pool:
#        # 线程池创建时的初始化线程数，默认为8
#        core-size: 2
#        # 线程池的最大线程数，默认为int最大值
#        max-size: 5
#        # 用来缓冲执行任务的队列，默认为int最大值
#        queue-capacity: 10
#        # 线程终止前允许保持空闲的时间
#        keep-alive: 60s
#        # 是否允许核心线程超时
#        allow-core-thread-timeout: true
#      shutdown:
#        # 是否等待剩余任务完成后才关闭应用
#        await-termination: false
#        # 等待剩余任务完成的最大时间
#        await-termination-period:
#      # 线程名的前缀，设置好了之后可以方便我们在日志中查看处理任务所在的线程池
#      thread-name-prefix: test-
