spring:
  main:
    allow-bean-definition-overriding: true

  shardingsphere:
    datasource:
      names: db0
      db0:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.31.21:3306/sharding?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
        username: root
        password: bmy@1688

    sharding:
      tables:
        user:
          actual-data-nodes: db0.user_$->{2023..2024}$->{(1..12).collect{m -> m.toString().padLeft(2, '0')}}
          table-strategy:
            standard:
              shardingColumn: create_date
              preciseAlgorithmClassName: com.lee.sharding.config.DatePreciseShardingAlgorithm
              rangeAlgorithmClassName: com.lee.sharding.config.DateRangeShardingAlgorithm
        info:
          actual-data-nodes: db0.info_$->{2023..2024}$->{(1..12).collect{m -> m.toString().padLeft(2, '0')}}
          table-strategy:
            standard:
              shardingColumn: create_date
              preciseAlgorithmClassName: com.lee.sharding.config.DatePreciseShardingAlgorithm
              rangeAlgorithmClassName: com.lee.sharding.config.DateRangeShardingAlgorithm
      bindingTables:
        - user,info

    props:
      sql:
        show: true

allow:
  range:
    query:
      with:
        inline:
          sharding: false

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml